# ?? Conexión con MySQL ???????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca
spring.datasource.username=root
spring.datasource.password=One piece 18

# ?? Configuración de JPA / Hibernate ?????????????????
# update: crea o actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
# true: muestra en consola las queries SQL generadas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ?? Puerto del servidor ???????????????????????????????
server.port=8080